// Mocks generated by Mockito 5.4.0 from annotations
// in elections/test/features/elections/repository/elections_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:elections/core/constants/params.dart' as _i6;
import 'package:elections/features/elections/data/base_elections_data_source.dart'
    as _i4;
import 'package:elections/features/elections/models/elections_model.dart'
    as _i2;
import 'package:elections/features/registrations/models/registration_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeElectionsModel_0 extends _i1.SmartFake
    implements _i2.ElectionsModel {
  _FakeElectionsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFireStoreUserDataModel_1 extends _i1.SmartFake
    implements _i3.FireStoreUserDataModel {
  _FakeFireStoreUserDataModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseElectionsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseElectionsDataSource extends _i1.Mock
    implements _i4.BaseElectionsDataSource {
  MockBaseElectionsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ElectionsModel> getAvailableElections() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableElections,
          [],
        ),
        returnValue: _i5.Future<_i2.ElectionsModel>.value(_FakeElectionsModel_0(
          this,
          Invocation.method(
            #getAvailableElections,
            [],
          ),
        )),
      ) as _i5.Future<_i2.ElectionsModel>);
  @override
  _i5.Future<void> electionVote(_i6.ElectionVoteParam? electionVoteParam) =>
      (super.noSuchMethod(
        Invocation.method(
          #electionVote,
          [electionVoteParam],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<_i3.FireStoreUserDataModel> getSignedInUserFromFireStore(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSignedInUserFromFireStore,
          [uid],
        ),
        returnValue: _i5.Future<_i3.FireStoreUserDataModel>.value(
            _FakeFireStoreUserDataModel_1(
          this,
          Invocation.method(
            #getSignedInUserFromFireStore,
            [uid],
          ),
        )),
      ) as _i5.Future<_i3.FireStoreUserDataModel>);
  @override
  _i5.Future<void> updateSignedInUserVoteStatus(
          _i3.FireStoreUserDataModel? newUserData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSignedInUserVoteStatus,
          [newUserData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Stream<_i7.DocumentSnapshot<Map<String, dynamic>>> getDocDataAsSnapshot(
    String? collectionName,
    String? collectionDocId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocDataAsSnapshot,
          [
            collectionName,
            collectionDocId,
          ],
        ),
        returnValue:
            _i5.Stream<_i7.DocumentSnapshot<Map<String, dynamic>>>.empty(),
      ) as _i5.Stream<_i7.DocumentSnapshot<Map<String, dynamic>>>);
  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
